language: node_js
node_js:
  - "16"
  
cache:
  directories:
  - node_modules

install:
  - npm install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
