language: node_js
node_js:
  - "14"  # Specify a version known to work with your system libraries
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
